# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e4b7f6b4d543c2ad1e97f6a7a27b1474d2d0b11f5a96bed2a9c4edbeb3843ec7dc6a1d50adeedba40184dd69a3d8b4d7ec3025a2e162f42f535393bc2a04d18

test:
  secret_key_base: 4e2f54ad08f39d6d6af1c9a4d8141a529b188a4abd3fdc26a9225209852175be137509ed5bfb74493b463492f9e54f6e2a944e09fae0321a25850c09afed1d79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
